### ISSUE TITLE
Please kill this crate

### ISSUE THREAD

**Issue by chris-morgan** [IvanUkhov/c#1]
This crate is a _terrible_ idea. What it amounts to is a saving of three letters and _a removal of version numbers_. So people will have no idea which version of libc they’ll be getting—so that this crate doesn’t have semver compatibility.

And sure, you could fix that by just making it duplicate all libc versions, but seriously, why would you even do that? It’s just lots of error-prone added work for no appreciable benefit and added confusion.

People are _using_ this (or at least downloading it), which is really bad. Please yank all versions of it with prejudice.

**Comment by IvanUkhov** [comment]
Thanks a lot for drawing my attention to this! As far as I remember, `c` seemed to me to be a better name for `libc`, and I naively thought I would manage to convince someone like @AlexCrichton to rename `libc` to `c`. So I reserved the name on crates.io. Anyway, I didn’t realize that people were actually using it. I have yanked all the versions. Thanks again!
